spring:
  application:
    name: server-furniture-ecommerce
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
server:
  port: 8085
  shutdown: graceful