spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8085/oauth2/callback/google"
            scope:
              - email
              - profile
              - openid
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000
server:
  port: 8085
  shutdown: graceful
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: "*"